name: Build, Test and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    uses: ./.github/workflows/common.yml

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Publish NuGet package
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
